title: Anatoliy Platonov
email: p4m.dev@gmail.com
description: >-
  Personal site with CV and blog. Just for fun :)
baseurl: ""
url: "https://p4m-dev.github.io"
twitter_username: dotofsp
github_username:  p4m-dev


theme: minima
plugins:
  - jekyll-feed
